---
abstract: 'Reconstruct Moo Objects'
author:
  - 'Jim Bacon <jim@nortx.com>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.59'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MooX-Role-Reconstruct
no_index:
  directory:
    - t
    - inc
requires:
  Role::Tiny: '0'
  Sub::Defer: '0'
  Sub::Quote: '0'
  perl: '5.006'
version: v0.1.2
